### ISSUE TITLE
Support for redundant networks (ST2110-7)

### ISSUE THREAD

**Issue by moze8** [nicolassturmel/media-network-manager-cloud#7]
Currently, there is no support for redundant networks. Is this something that is being developed/planned. And can I contribute to this?

**Comment by nicolassturmel** [comment]
Hi Moze8

You might have to launch the services by hand but if the PC has access to networks A and B,
it should be possible.
There are maybe some bugs though ! I can already see some, and will fix them ASAP !

What is your experience so far ?

You can contribute as much as you want, from testing to feature requesting to coding !
