### ISSUE TITLE
OS X - onopen js error

### ISSUE THREAD

**Issue by mattcph** [nicolassturmel/media-network-manager-cloud#8]
![Screen Shot 2020-04-28 at 10 57 28 AM](https://user-images.githubusercontent.com/420679/80468268-401feb00-893f-11ea-9708-f14b271fbec3.png)

Only had one device on the network (bonjour)

**Comment by nicolassturmel** [comment]
Hi Matt, this is due to OSX sand boxing and the app saving files at the wrong place.
You can:
- find the right location to save to and amend the code ;) - I shall do that when I got time
- copy the app in the Application folder, seems it solves the problem

**Comment by nicolassturmel** [comment]
Done on version 1-2
