### ISSUE TITLE
link opening in the wrong window 

### ISSUE THREAD

**Issue by Harald-pmp** [nicolassturmel/media-network-manager-cloud#9]
Hi Nicolas
If you click/link to the MERGING TECH... webinterface link from the top list, the settings page will be shown in an add. window, which can be closed afterwards. But if you select one device in the top list and use the "Merging Tech..." link on the left column, the settings or web gui will be shown in fullscreen mode - replacing the MnMs-GUI. As I did not find any "return to main windows" button, you close MnMs when closing the window... 
Best regards,
Harald

**Comment by nicolassturmel** [comment]
Should be good on version 1
